///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LCAD
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateReservation recording.
    /// </summary>
    [TestModule("87f31820-c612-4487-bfa2-1ea018621d6b", ModuleType.Recording, 1)]
    public partial class CreateReservation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LCADRepository repository.
        /// </summary>
        public static LCADRepository repo = LCADRepository.Instance;

        static CreateReservation instance = new CreateReservation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateReservation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateReservation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogistiCADArizona.ReservationsToolButton' at 17;16.", repo.LogistiCADArizona.ReservationsToolButtonInfo, new RecordItemIndex(0));
            repo.LogistiCADArizona.ReservationsToolButton.Click("17;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogistiCADArizona.Close' at 15;5.", repo.LogistiCADArizona.CloseInfo, new RecordItemIndex(1));
            repo.LogistiCADArizona.Close.Click("15;5");
            Delay.Milliseconds(7110);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
