///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LCAD
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LCADRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("39f306a8-e45c-4e69-8c5d-bcf88565fcc3")]
    public partial class LCADRepository : RepoGenBaseFolder
    {
        static LCADRepository instance = new LCADRepository();
        LCADRepositoryFolders.LogistiCADLoginAppFolder _logisticadlogin;
        LCADRepositoryFolders.SelectCallCenterAppFolder _selectcallcenter;
        LCADRepositoryFolders.LogistiCADArizonaAppFolder _logisticadarizona;
        LCADRepositoryFolders.LogistiCADExeAppFolder _logisticadexe;
        LCADRepositoryFolders.LogistiCADSystemAppFolder _logisticadsystem;
        LCADRepositoryFolders.FormHash32770AppFolder _formhash32770;

        /// <summary>
        /// Gets the singleton class instance representing the LCADRepository element repository.
        /// </summary>
        [RepositoryFolder("39f306a8-e45c-4e69-8c5d-bcf88565fcc3")]
        public static LCADRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LCADRepository() 
            : base("LCADRepository", "/", null, 0, false, "39f306a8-e45c-4e69-8c5d-bcf88565fcc3", ".\\RepositoryImages\\LCADRepository39f306a8.rximgres")
        {
            _logisticadlogin = new LCADRepositoryFolders.LogistiCADLoginAppFolder(this);
            _selectcallcenter = new LCADRepositoryFolders.SelectCallCenterAppFolder(this);
            _logisticadarizona = new LCADRepositoryFolders.LogistiCADArizonaAppFolder(this);
            _logisticadexe = new LCADRepositoryFolders.LogistiCADExeAppFolder(this);
            _logisticadsystem = new LCADRepositoryFolders.LogistiCADSystemAppFolder(this);
            _formhash32770 = new LCADRepositoryFolders.FormHash32770AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("39f306a8-e45c-4e69-8c5d-bcf88565fcc3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LogistiCADLogin folder.
        /// </summary>
        [RepositoryFolder("62b13266-888a-46dd-bde6-d05e93f5ac79")]
        public virtual LCADRepositoryFolders.LogistiCADLoginAppFolder LogistiCADLogin
        {
            get { return _logisticadlogin; }
        }

        /// <summary>
        /// The SelectCallCenter folder.
        /// </summary>
        [RepositoryFolder("9878914c-64c3-4427-a1c4-c2a119d4a3c4")]
        public virtual LCADRepositoryFolders.SelectCallCenterAppFolder SelectCallCenter
        {
            get { return _selectcallcenter; }
        }

        /// <summary>
        /// The LogistiCADArizona folder.
        /// </summary>
        [RepositoryFolder("d8e0f9cb-ac86-4c6e-b3a4-124505e4599f")]
        public virtual LCADRepositoryFolders.LogistiCADArizonaAppFolder LogistiCADArizona
        {
            get { return _logisticadarizona; }
        }

        /// <summary>
        /// The LogistiCADExe folder.
        /// </summary>
        [RepositoryFolder("f0045169-6d43-4962-aca2-02467d38043a")]
        public virtual LCADRepositoryFolders.LogistiCADExeAppFolder LogistiCADExe
        {
            get { return _logisticadexe; }
        }

        /// <summary>
        /// The LogistiCADSystem folder.
        /// </summary>
        [RepositoryFolder("e6eaab1d-c468-4ff6-a4c9-a1ef5cf669df")]
        public virtual LCADRepositoryFolders.LogistiCADSystemAppFolder LogistiCADSystem
        {
            get { return _logisticadsystem; }
        }

        /// <summary>
        /// The FormHash32770 folder.
        /// </summary>
        [RepositoryFolder("e6279422-4a17-40dc-a2ab-495e8dbf46ee")]
        public virtual LCADRepositoryFolders.FormHash32770AppFolder FormHash32770
        {
            get { return _formhash32770; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LCADRepositoryFolders
    {
        /// <summary>
        /// The LogistiCADLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("62b13266-888a-46dd-bde6-d05e93f5ac79")]
        public partial class LogistiCADLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _euseridInfo;
            RepoItemInfo _epasswordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new LogistiCADLogin  folder.
            /// </summary>
            public LogistiCADLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogistiCADLogin", "/form[@name='PasswordDialogForm']", parentFolder, 30000, null, true, "62b13266-888a-46dd-bde6-d05e93f5ac79", "")
            {
                _euseridInfo = new RepoItemInfo(this, "EUserID", "text[@name='eUserID']", "text[@name='eUserID']", 30000, null, "335cec5f-2ae2-49f2-9eb1-52783f32a457");
                _epasswordInfo = new RepoItemInfo(this, "EPassword", "text[@name='ePassword']", "text[@name='ePassword']", 30000, null, "545649a4-c9ef-4952-87b3-eeb0746924db");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@name='btnOK']", "button[@name='btnOK']", 30000, null, "a0b31b39-5ccd-4265-9e22-e2640849c5d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("62b13266-888a-46dd-bde6-d05e93f5ac79")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("62b13266-888a-46dd-bde6-d05e93f5ac79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EUserID item.
            /// </summary>
            [RepositoryItem("335cec5f-2ae2-49f2-9eb1-52783f32a457")]
            public virtual Ranorex.Text EUserID
            {
                get
                {
                    return _euseridInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EUserID item info.
            /// </summary>
            [RepositoryItemInfo("335cec5f-2ae2-49f2-9eb1-52783f32a457")]
            public virtual RepoItemInfo EUserIDInfo
            {
                get
                {
                    return _euseridInfo;
                }
            }

            /// <summary>
            /// The EPassword item.
            /// </summary>
            [RepositoryItem("545649a4-c9ef-4952-87b3-eeb0746924db")]
            public virtual Ranorex.Text EPassword
            {
                get
                {
                    return _epasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EPassword item info.
            /// </summary>
            [RepositoryItemInfo("545649a4-c9ef-4952-87b3-eeb0746924db")]
            public virtual RepoItemInfo EPasswordInfo
            {
                get
                {
                    return _epasswordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a0b31b39-5ccd-4265-9e22-e2640849c5d5")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a0b31b39-5ccd-4265-9e22-e2640849c5d5")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The SelectCallCenterAppFolder folder.
        /// </summary>
        [RepositoryFolder("9878914c-64c3-4427-a1c4-c2a119d4a3c4")]
        public partial class SelectCallCenterAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _callcenterlistboxInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new SelectCallCenter  folder.
            /// </summary>
            public SelectCallCenterAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectCallCenter", "/form[@name='SelectCallCenterDialog']", parentFolder, 30000, null, true, "9878914c-64c3-4427-a1c4-c2a119d4a3c4", "")
            {
                _callcenterlistboxInfo = new RepoItemInfo(this, "CallCenterListBox", "list[@name='CallCenterListBox']", "list[@name='CallCenterListBox']", 30000, null, "f4e4715d-6653-4283-8a60-949291cb5c75");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@name='OKButton']", "button[@name='OKButton']", 30000, null, "c5b04a84-746e-48fb-acb4-6e248e7dfa19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9878914c-64c3-4427-a1c4-c2a119d4a3c4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9878914c-64c3-4427-a1c4-c2a119d4a3c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CallCenterListBox item.
            /// </summary>
            [RepositoryItem("f4e4715d-6653-4283-8a60-949291cb5c75")]
            public virtual Ranorex.List CallCenterListBox
            {
                get
                {
                    return _callcenterlistboxInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The CallCenterListBox item info.
            /// </summary>
            [RepositoryItemInfo("f4e4715d-6653-4283-8a60-949291cb5c75")]
            public virtual RepoItemInfo CallCenterListBoxInfo
            {
                get
                {
                    return _callcenterlistboxInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("c5b04a84-746e-48fb-acb4-6e248e7dfa19")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("c5b04a84-746e-48fb-acb4-6e248e7dfa19")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The LogistiCADArizonaAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8e0f9cb-ac86-4c6e-b3a4-124505e4599f")]
        public partial class LogistiCADArizonaAppFolder : RepoGenBaseFolder
        {
            ReservationsToolButtonInfoClass _reservationstoolbuttonInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new LogistiCADArizona  folder.
            /// </summary>
            public LogistiCADArizonaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogistiCADArizona", "/form[@name='MainForm']", parentFolder, 30000, null, true, "d8e0f9cb-ac86-4c6e-b3a4-124505e4599f", "")
            {
                _reservationstoolbuttonInfo = new ReservationsToolButtonInfoClass(this);
                _closeInfo = new RepoItemInfo(this, "Close", "form[@name>'TripResForm_ul0ieMVW9kODK']/?/?/form[@automationid='65280']/?/?/button[@automationid='Close']", ".//form[@automationid='65280']/titlebar[@automationid='TitleBar']/button[@automationid='Close']", 30000, null, "d70bbd1c-bf3a-4d5c-a50a-0bfdf9dc7b88");
            }

            /// <summary>
            /// The ReservationsToolButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5f46db43-6d11-4db4-bfbe-a91e2e6baad5")]
            public class ReservationsToolButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ReservationsToolButtonInfoClass class constructor.
                /// </summary>
                public ReservationsToolButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ReservationsToolButton", "?/?/toolbar[@name='LCADToolBar']/button[@name='ReservationsToolButton']", 30000, null, "5f46db43-6d11-4db4-bfbe-a91e2e6baad5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("1b5d4bc4-0fb4-43f3-8ea7-e3770de2576d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("1b5d4bc4-0fb4-43f3-8ea7-e3770de2576d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1b5d4bc4-0fb4-43f3-8ea7-e3770de2576d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1b5d4bc4-0fb4-43f3-8ea7-e3770de2576d", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8e0f9cb-ac86-4c6e-b3a4-124505e4599f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8e0f9cb-ac86-4c6e-b3a4-124505e4599f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReservationsToolButton item.
            /// </summary>
            [RepositoryItem("5f46db43-6d11-4db4-bfbe-a91e2e6baad5")]
            public virtual Ranorex.Button ReservationsToolButton
            {
                get
                {
                    return _reservationstoolbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReservationsToolButton item info.
            /// </summary>
            [RepositoryItemInfo("5f46db43-6d11-4db4-bfbe-a91e2e6baad5")]
            public virtual ReservationsToolButtonInfoClass ReservationsToolButtonInfo
            {
                get
                {
                    return _reservationstoolbuttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("d70bbd1c-bf3a-4d5c-a50a-0bfdf9dc7b88")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("d70bbd1c-bf3a-4d5c-a50a-0bfdf9dc7b88")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The LogistiCADExeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0045169-6d43-4962-aca2-02467d38043a")]
        public partial class LogistiCADExeAppFolder : RepoGenBaseFolder
        {
            ButtonOKInfoClass _buttonokInfo;

            /// <summary>
            /// Creates a new LogistiCADExe  folder.
            /// </summary>
            public LogistiCADExeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogistiCADExe", "/form[@title='LogistiCAD.exe']", parentFolder, 30000, null, true, "f0045169-6d43-4962-aca2-02467d38043a", "")
            {
                _buttonokInfo = new ButtonOKInfoClass(this);
            }

            /// <summary>
            /// The ButtonOKInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("5746e2a2-4268-46ba-b576-f432c989dd7e")]
            public class ButtonOKInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ButtonOKInfoClass class constructor.
                /// </summary>
                public ButtonOKInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ButtonOK", "button[@controlid='2']", 30000, null, "5746e2a2-4268-46ba-b576-f432c989dd7e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("87635b53-89c6-478d-b0c2-af818d0efdc9")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("87635b53-89c6-478d-b0c2-af818d0efdc9");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("87635b53-89c6-478d-b0c2-af818d0efdc9")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("87635b53-89c6-478d-b0c2-af818d0efdc9", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0045169-6d43-4962-aca2-02467d38043a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0045169-6d43-4962-aca2-02467d38043a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("5746e2a2-4268-46ba-b576-f432c989dd7e")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("5746e2a2-4268-46ba-b576-f432c989dd7e")]
            public virtual ButtonOKInfoClass ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The LogistiCADSystemAppFolder folder.
        /// </summary>
        [RepositoryFolder("e6eaab1d-c468-4ff6-a4c9-a1ef5cf669df")]
        public partial class LogistiCADSystemAppFolder : RepoGenBaseFolder
        {
            ButtonOKInfoClass _buttonokInfo;

            /// <summary>
            /// Creates a new LogistiCADSystem  folder.
            /// </summary>
            public LogistiCADSystemAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogistiCADSystem", "/form[@title='LogistiCAD System']", parentFolder, 30000, null, true, "e6eaab1d-c468-4ff6-a4c9-a1ef5cf669df", "")
            {
                _buttonokInfo = new ButtonOKInfoClass(this);
            }

            /// <summary>
            /// The ButtonOKInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("50a2077a-880d-4702-a910-e0a9b86b49e4")]
            public class ButtonOKInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ButtonOKInfoClass class constructor.
                /// </summary>
                public ButtonOKInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ButtonOK", "button[@text='OK']", 30000, null, "50a2077a-880d-4702-a910-e0a9b86b49e4")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("357f8df4-af1d-4d49-8403-20d559329d78")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("357f8df4-af1d-4d49-8403-20d559329d78");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("357f8df4-af1d-4d49-8403-20d559329d78")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("357f8df4-af1d-4d49-8403-20d559329d78", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6eaab1d-c468-4ff6-a4c9-a1ef5cf669df")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6eaab1d-c468-4ff6-a4c9-a1ef5cf669df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("50a2077a-880d-4702-a910-e0a9b86b49e4")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("50a2077a-880d-4702-a910-e0a9b86b49e4")]
            public virtual ButtonOKInfoClass ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The FormHash32770AppFolder folder.
        /// </summary>
        [RepositoryFolder("e6279422-4a17-40dc-a2ab-495e8dbf46ee")]
        public partial class FormHash32770AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new FormHash32770  folder.
            /// </summary>
            public FormHash32770AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormHash32770", "/form[@class='#32770']", parentFolder, 30000, null, true, "e6279422-4a17-40dc-a2ab-495e8dbf46ee", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6279422-4a17-40dc-a2ab-495e8dbf46ee")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6279422-4a17-40dc-a2ab-495e8dbf46ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
